name: nectar
description: A starting point for Dart libraries or applications.
version: 1.0.5
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  get_it: ^7.6.4
  logger: ^2.0.2+1
  uuid: ^4.3.1
  mysql_client: ^0.0.27
  mysql1: ^0.20.0
#  shelf: ^1.4.1
#  shelf_router: ^1.1.4
  shelf_plus: ^1.7.0
  dart_jsonwebtoken: ^2.12.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.5.3
