name: nectar_generator
description: Generate all helper classes for nectar library.
version: 1.2.0
publish_to: none

environment:
  sdk: ^3.2.3

dependencies:
  analyzer: ^6.3.0
  build: ^2.4.1
  build_config: ^1.1.1
  code_builder: ^4.9.0
  source_gen: ^1.5.0
  logging: ^1.2.0
  mysql1: ^0.20.0
  collection: ^1.18.0
  nectar:
    git:
      url: https://github.com/minelifes/nectar.git
      path: ./nectar/
#  nectar:
#    path: ../nectar

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.4.7
  test: ^1.5.3
  pool: ^1.5.0
  json_serializable: ^6.7.1