name: nectar_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  nectar:
    path: ../nectar
  uuid: ^4.3.1

dev_dependencies:
  lints: ^3.0.0
  nectar_generator:
    path: ../nectar_generator
  build_runner: ^2.4.7
  test: ^1.5.3
